language: rust
cache: cargo
branches:
  only:
  - master
before_script:
  - cargo install --force mdbook
script:
  - mkdir -p src
  - rsync -av --exclude='.*' . src
  - mdbook build --dest-dir build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: build
  on:
    branch: master
